name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      # - name: Install SSH key
      #   uses: webfactory/ssh-agent@v0.5.3
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_ACCESS_TOKEN_HOSTINGER_BACKEND }}

      - name: Install SSH key and Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_HOSTINGER_BACKEND }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE_HOSTINGER_BACKEND }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD_HOSTINGER_BACKEND }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_HOSTINGER_WINKSEN }}
        run: |
          export GITHUB_TOKEN
          export SSH_PASSWORD
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no u167377926@62.72.37.84 -p 65002 "cd domains/winksen.com/public_html/web-backend/ && GIT_ASKPASS=/bin/echo GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=no -i /dev/stdin' git pull origin main && composer install && php artisan migrate --force"
